apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fist-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    helm:
      parameters:
      - name: ingress.inghost
        value: jenkins-argo.k8s-13.sa
    repoURL: https://nataliabelogolovaya.github.io/helm-charts/jenkins/
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
